repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pdm
        language: system
        types: [python]
        args:
          [
            "run",
            "pylint",
            "-rn",
            "-sn",
          ]
      - id: pytest
        name: pytest
        entry: pdm
        language: system
        types: [python]
        args:
          [
            "run",
            "pytest",
            "-m",
            "not slow",
        ]
        pass_filenames: false
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
