version: "3.9"

services:
  nvim:
    build:
      context: .
      args:
        - base=cblessing24/blessed-nvim:git-ef53d5a9e795f721acae73c6a23933c2004a08ff
    volumes:
      - .:/src
      - pypackages:/src/__pypackages__
    command: "nvim"
  build:
    build: .
    volumes:
      - .:/src
    entrypoint: ["pdm"]
    command: "build"
  pytest:
    build: .
    volumes:
      - .:/src
      - pypackages:/src/__pypackages__
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER=1
    networks:
      - test
    entrypoint: ["pdm", "run", "pytest"]
  black:
    build: .
    entrypoint: ["pdm", "run", "black"]
    command: ["--check", "--diff", "."]
  isort:
    build: .
    entrypoint: ["pdm", "run", "isort"]
    command: ["--check-only", "--diff", "."]
  mypy:
    build: .
    volumes:
      - mypy-cache:/src/.mypy_cache
    entrypoint: ["pdm", "run", "mypy"]
  flake8:
    build: .
    entrypoint: ["pdm", "run", "flake8"]
    command: "."
  pylint:
    build: .
    entrypoint: ["pdm", "run", "pylint"]
    command: "compenv"

volumes:
  pypackages:
  mypy-cache:

networks:
  test:
