version: "3.9"

services:
  nvim:
    build:
      context: .
      args:
        - base=cblessing24/docker-dev:426adac9c4705963829e17e862082052fa885169
    volumes:
      - .:/src
    command: "nvim"

