version: "3.9"
name: compenv
services:
  dev:
    build:
      context: .
      args:
        BASE: cblessing24/python3.8:latest
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - compenv:/src
    environment:
      - DOCKER=1
    networks:
      - test
    command: "tmux"
  build:
    image: cblessing24/compenv:latest
    volumes:
      - .:/src
    entrypoint: ["pdm"]
    command: "build"
  pytest:
    image: cblessing24/compenv:latest
    volumes:
      - compenv:/src
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER=1
    networks:
      - test
    command: ["pytest"]
  pytest_github:
    image: cblessing24/compenv:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./reports:/src/reports
    environment:
      - DOCKER=1
    networks:
      - test
    command: [
      "pytest", 
      "--cov", 
      "--cov-report=xml:/src/reports/coverage.xml",
      "--cov-config=pyproject.toml", # Workaround for https://github.com/nedbat/coveragepy/issues/512
    ]
  black:
    image: cblessing24/compenv:latest
    command: ["black", "--check", "--diff", "."]
  isort:
    image: cblessing24/compenv:latest
    command: ["isort", "--check-only", "--diff", "."]
  mypy:
    image: cblessing24/compenv:latest
    command: ["mypy"]
  flake8:
    image: cblessing24/compenv:latest
    command: ["flake8", "."]
  pylint:
    image: cblessing24/compenv:latest
    command: ["pylint", "compenv"]

volumes:
  compenv:

networks:
  test:
