version: "3.9"

services:
  nvim:
    build:
      context: .
      args:
        - base=cblessing24/blessed-nvim:git-ef53d5a9e795f721acae73c6a23933c2004a08ff
    volumes:
      - .:/src
    command: "nvim"

