class Connection:
    def start_transaction(self) -> None: ...
    def commit_transaction(self) -> None: ...
    def cancel_transaction(self) -> None: ...
    @property
    def in_transaction(self) -> bool: ...
