class Connection:
    def __init__(self, host: str, user: str, password: str) -> None: ...
    def start_transaction(self) -> None: ...
    def commit_transaction(self) -> None: ...
    def cancel_transaction(self) -> None: ...
    @property
    def in_transaction(self) -> bool: ...
    def close(self) -> None: ...
