from typing import Any, Dict, Iterator, Mapping, Union

_PrimaryKey = Dict[str, Union[str, float, int]]

class Table:
    def insert1(self, row: Mapping[str, Any]) -> None: ...
    def delete_quick(self) -> None: ...
    def __contains__(self, other: object) -> bool: ...
    def __and__(self, restriction: _PrimaryKey) -> Table: ...
    def __iter__(self) -> Iterator[_PrimaryKey]: ...
    def __len__(self) -> int: ...
