from typing import Any, Iterator, Mapping, Union

Entity = Mapping[str, Union[str, float, int]]

class Table:
    connection: Any
    database: str
    definition: str
    def insert1(self, row: Entity) -> None: ...
    def delete_quick(self) -> None: ...
    def __contains__(self, other: object) -> bool: ...
    def __and__(self, restriction: Entity) -> Table: ...
    def __iter__(self) -> Iterator[Entity]: ...
    def __len__(self) -> int: ...

class AutoPopulatedTable(Table):
    def make(self, key: Entity) -> None: ...
