name: Test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run tests and generate coverage report
      run: docker-compose run pytest --cov --cov-report=xml:/src/reports/coverage.xml
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: /src/reports/coverage.xml
        verbose: true
