name: Test

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run tests and generate coverage report
      run: ./workflows/test.sh
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
